In [653]:
import pandas as pd

df = pd.read_csv('Book1.csv')
df.head()

       date product  quantity_sold  price
0  1/1/2024       A             10    100
1  1/2/2024       A             12    100
2  1/3/2024       B              5    200
3  1/4/2024       A             15    100
4  1/5/2024       B              7    200

In [654]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10 non-null     str
 1   product        10 non-null     str
 2   quantity_sold  10 non-null     int64
 3   price          10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes

       quantity_sold       price
count      10.000000   10.000000
mean       12.300000  140.000000
std         6.129165   51.639778
min         5.000000  100.000000
25%         7.250000  100.000000
50%        11.000000  100.000000
75%        17.250000  200.000000
max        22.000000  200.000000

Convert Date (Now Python understands time)

In [655]:
df['date'] = pd.to_datetime(df['date'])
print(df['date'])

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
6   2024-01-07
7   2024-01-08
8   2024-01-09
9   2024-01-10
Name: date, dtype: datetime64[us]

Create New Features 
Now model can learn patterns like:
1.weekends
2.monthly trends

In [656]:
df["day"] = df["date"].dt.day
df["month"] = df["date"].dt.month
df['day_of_week'] = df['date'].dt.dayofweek

Basic Analysis :
Total sales per product

In [657]:
print(df.groupby('product')['quantity_sold'].sum())

product
A    97
B    26
Name: quantity_sold, dtype: int64

Average sales

In [658]:
print(df['quantity_sold'].mean())

12.3

Highest sales day

In [659]:
print(df[df['quantity_sold'] == df['quantity_sold'].max()])

        date product  quantity_sold  price  day  month  day_of_week
9 2024-01-10       A             22    100   10      1            2

In [660]:
df =pd.get_dummies(df, columns=['product'])

In [661]:
X = df[["price", "day", "month", "day_of_week", "product_A", "product_B"]]
Y = df["quantity_sold"]

In [662]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [663]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [664]:
predictions = model.predict(X_test)
print("Actual:", list(Y_test)[:5])
print('predicted:', predictions)

Actual: [6, 12]
predicted: [ 9.60784314 12.42647059]

In [665]:
print('Accuracy:', model.score(X_test, Y_test))

Accuracy: 0.26675504079627566

In [666]:
new_data = [[100,11,1,3,1,0]]
print(model.predict(new_data))
print('Accuracy:', model.score(X_test, Y_test))

[23.08823529]
Accuracy: 0.26675504079627566

C:\Users\ASUS\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [667]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [668]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [669]:
from sklearn.metrics import mean_absolute_error

Y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(Y_test, Y_pred))

MAE: 2.0171568627450984

In [670]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, Y_train)

RandomForestRegressor()

In [671]:
print('Accuracy : ' , model.score(X_test,Y_test))

Accuracy :  -1.1288722222222218